// For reference only - this is now a table in Supabase
//seeded data
// let recipeBook = [
//     {id: generated by DB,
//         recipeName: "Honey Garlic Chicken", //text
//         ingredients: ["chicken thighs or breasts", "honey", "soy sauce", "minced garlic", "olive oil"], //json
//         directions: "Sear chicken in olive oil. Mix honey, soy sauce and garlic, pour over, simmer 10-12 minutes until sticky." //text
//     }
//  ]